# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: ur5_1
  joint_model_group_pose: arm_1_up
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - ur5_1_shoulder_pan_joint
    - ur5_1_shoulder_lift_joint
    - ur5_1_elbow_joint
    - ur5_1_wrist_1_joint
    - ur5_1_wrist_2_joint
    - ur5_1_wrist_3_joint
    - ur5_1_gripper_finger1_joint
    - ur5_2_shoulder_pan_joint
    - ur5_2_shoulder_lift_joint
    - ur5_2_elbow_joint
    - ur5_2_wrist_1_joint
    - ur5_2_wrist_2_joint
    - ur5_2_wrist_3_joint
    - ur5_2_gripper_finger1_joint
    - ur5_3_shoulder_pan_joint
    - ur5_3_shoulder_lift_joint
    - ur5_3_elbow_joint
    - ur5_3_wrist_1_joint
    - ur5_3_wrist_2_joint
    - ur5_3_wrist_3_joint
    - ur5_3_gripper_finger1_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ur5_1_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_1_shoulder_pan_joint
      - ur5_1_shoulder_lift_joint
      - ur5_1_elbow_joint
      - ur5_1_wrist_1_joint
      - ur5_1_wrist_2_joint
      - ur5_1_wrist_3_joint
  - name: ur5_2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_2_shoulder_pan_joint
      - ur5_2_shoulder_lift_joint
      - ur5_2_elbow_joint
      - ur5_2_wrist_1_joint
      - ur5_2_wrist_2_joint
      - ur5_2_wrist_3_joint
  - name: ur5_1_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_1_gripper_finger1_joint
  - name: ur5_2_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_2_gripper_finger1_joint
  - name: ur5_3_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_3_shoulder_pan_joint
      - ur5_3_shoulder_lift_joint
      - ur5_3_elbow_joint
      - ur5_3_wrist_1_joint
      - ur5_3_wrist_2_joint
      - ur5_3_wrist_3_joint
  - name: ur5_3_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_3_gripper_finger1_joint
  - name: dual_ur_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_1_shoulder_pan_joint
      - ur5_1_shoulder_lift_joint
      - ur5_1_elbow_joint
      - ur5_1_wrist_1_joint
      - ur5_1_wrist_2_joint
      - ur5_1_wrist_3_joint
      - ur5_1_gripper_finger1_joint
      - ur5_2_shoulder_pan_joint
      - ur5_2_shoulder_lift_joint
      - ur5_2_elbow_joint
      - ur5_2_wrist_1_joint
      - ur5_2_wrist_2_joint
      - ur5_2_wrist_3_joint
      - ur5_2_gripper_finger1_joint
  - name: multiple_ur_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_1_shoulder_pan_joint
      - ur5_1_shoulder_lift_joint
      - ur5_1_elbow_joint
      - ur5_1_wrist_1_joint
      - ur5_1_wrist_2_joint
      - ur5_1_wrist_3_joint
      - ur5_1_gripper_finger1_joint
      - ur5_2_shoulder_pan_joint
      - ur5_2_shoulder_lift_joint
      - ur5_2_elbow_joint
      - ur5_2_wrist_1_joint
      - ur5_2_wrist_2_joint
      - ur5_2_wrist_3_joint
      - ur5_2_gripper_finger1_joint
      - ur5_3_shoulder_pan_joint
      - ur5_3_shoulder_lift_joint
      - ur5_3_elbow_joint
      - ur5_3_wrist_1_joint
      - ur5_3_wrist_2_joint
      - ur5_3_wrist_3_joint
      - ur5_3_gripper_finger1_joint